#!/bin/bash

echo "=== MANUAL INFRASTRUCTURE EXPORTER SETUP ==="
echo ""
echo "Run these commands individually in your terminal:"
echo ""

echo "# 1. Start Node Exporter (System Metrics)"
echo "docker run -d --name node-exporter --network host \\"
echo "  -v /proc:/host/proc:ro \\"
echo "  -v /sys:/host/sys:ro \\"
echo "  -v /:/rootfs:ro \\"
echo "  prom/node-exporter \\"
echo "  --path.procfs=/host/proc \\"
echo "  --path.rootfs=/rootfs \\"
echo "  --path.sysfs=/host/sys"
echo ""

echo "# 2. Start PostgreSQL Exporter (Database Metrics)"
echo "docker run -d --name postgres-exporter --network host \\"
echo "  -e DATA_SOURCE_NAME='postgresql://auth_user:auth_password@localhost:5432/auth_service?sslmode=disable' \\"
echo "  prometheuscommunity/postgres-exporter"
echo ""

echo "# 3. Start Kafka Exporter (Message Queue Metrics)"
echo "docker run -d --name kafka-exporter --network host \\"
echo "  -e KAFKA_SERVER=localhost:9092 \\"
echo "  danielqsj/kafka-exporter \\"
echo "  --kafka.server=localhost:9092"
echo ""

echo "# 4. Start cAdvisor (Container Metrics)"
echo "docker run -d --name cadvisor --network host \\"
echo "  -v /:/rootfs:ro \\"
echo "  -v /var/run:/var/run:ro \\"
echo "  -v /sys:/sys:ro \\"
echo "  -v /var/lib/docker:/var/lib/docker:ro \\"
echo "  -v /dev/disk:/dev/disk:ro \\"
echo "  --privileged \\"
echo "  gcr.io/cadvisor/cadvisor"
echo ""

echo "# 5. Verify all exporters are running:"
echo "docker ps | grep -E '(node-exporter|postgres-exporter|kafka-exporter|cadvisor)'"
echo ""

echo "# 6. Test metrics endpoints:"
echo "curl http://localhost:9100/metrics  # Node"
echo "curl http://localhost:9187/metrics  # PostgreSQL"
echo "curl http://localhost:9308/metrics  # Kafka"
echo "curl http://localhost:8080/metrics  # cAdvisor"
echo ""

echo "# 7. Check Prometheus targets:"
echo "curl http://localhost:9090/targets"
echo ""

echo "=== EXPECTED METRICS ==="
echo ""
echo "After starting exporters, you should see:"
echo "- System CPU, memory, disk, network metrics"
echo "- Database connection pools, query performance"
echo "- Kafka message rates, consumer lag"
echo "- Container resource usage per service"
echo ""

echo "=== GRAFANA DASHBOARDS ==="
echo ""
echo "Access Grafana: http://localhost:3000"
echo ""
echo "Available dashboards:"
echo "- Auth Service Overview"
echo "- Auth Service Comprehensive Monitoring"
echo "- Auth Service Logs"
echo ""

echo "Add infrastructure panels to existing dashboards or create new ones!"
