// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.20.3
// source: admin.proto

package admin

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AdminService_RecordUserCreated_FullMethodName = "/admin.AdminService/RecordUserCreated"
	AdminService_RecordUserUpdated_FullMethodName = "/admin.AdminService/RecordUserUpdated"
	AdminService_RecordUserDeleted_FullMethodName = "/admin.AdminService/RecordUserDeleted"
	AdminService_GetUserEvents_FullMethodName     = "/admin.AdminService/GetUserEvents"
)

// AdminServiceClient is the client API for AdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AdminService handles administrative operations
type AdminServiceClient interface {
	// RecordUserCreated records a user creation event
	RecordUserCreated(ctx context.Context, in *UserCreatedRequest, opts ...grpc.CallOption) (*UserCreatedResponse, error)
	// RecordUserUpdated records a user update event
	RecordUserUpdated(ctx context.Context, in *UserUpdatedRequest, opts ...grpc.CallOption) (*UserUpdatedResponse, error)
	// RecordUserDeleted records a user deletion event
	RecordUserDeleted(ctx context.Context, in *UserDeletedRequest, opts ...grpc.CallOption) (*UserDeletedResponse, error)
	// GetUserEvents retrieves user events
	GetUserEvents(ctx context.Context, in *GetUserEventsRequest, opts ...grpc.CallOption) (*GetUserEventsResponse, error)
}

type adminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminServiceClient(cc grpc.ClientConnInterface) AdminServiceClient {
	return &adminServiceClient{cc}
}

func (c *adminServiceClient) RecordUserCreated(ctx context.Context, in *UserCreatedRequest, opts ...grpc.CallOption) (*UserCreatedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserCreatedResponse)
	err := c.cc.Invoke(ctx, AdminService_RecordUserCreated_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) RecordUserUpdated(ctx context.Context, in *UserUpdatedRequest, opts ...grpc.CallOption) (*UserUpdatedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserUpdatedResponse)
	err := c.cc.Invoke(ctx, AdminService_RecordUserUpdated_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) RecordUserDeleted(ctx context.Context, in *UserDeletedRequest, opts ...grpc.CallOption) (*UserDeletedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserDeletedResponse)
	err := c.cc.Invoke(ctx, AdminService_RecordUserDeleted_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) GetUserEvents(ctx context.Context, in *GetUserEventsRequest, opts ...grpc.CallOption) (*GetUserEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserEventsResponse)
	err := c.cc.Invoke(ctx, AdminService_GetUserEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminServiceServer is the server API for AdminService service.
// All implementations must embed UnimplementedAdminServiceServer
// for forward compatibility.
//
// AdminService handles administrative operations
type AdminServiceServer interface {
	// RecordUserCreated records a user creation event
	RecordUserCreated(context.Context, *UserCreatedRequest) (*UserCreatedResponse, error)
	// RecordUserUpdated records a user update event
	RecordUserUpdated(context.Context, *UserUpdatedRequest) (*UserUpdatedResponse, error)
	// RecordUserDeleted records a user deletion event
	RecordUserDeleted(context.Context, *UserDeletedRequest) (*UserDeletedResponse, error)
	// GetUserEvents retrieves user events
	GetUserEvents(context.Context, *GetUserEventsRequest) (*GetUserEventsResponse, error)
	mustEmbedUnimplementedAdminServiceServer()
}

// UnimplementedAdminServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdminServiceServer struct{}

func (UnimplementedAdminServiceServer) RecordUserCreated(context.Context, *UserCreatedRequest) (*UserCreatedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecordUserCreated not implemented")
}
func (UnimplementedAdminServiceServer) RecordUserUpdated(context.Context, *UserUpdatedRequest) (*UserUpdatedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecordUserUpdated not implemented")
}
func (UnimplementedAdminServiceServer) RecordUserDeleted(context.Context, *UserDeletedRequest) (*UserDeletedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecordUserDeleted not implemented")
}
func (UnimplementedAdminServiceServer) GetUserEvents(context.Context, *GetUserEventsRequest) (*GetUserEventsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserEvents not implemented")
}
func (UnimplementedAdminServiceServer) mustEmbedUnimplementedAdminServiceServer() {}
func (UnimplementedAdminServiceServer) testEmbeddedByValue()                      {}

// UnsafeAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminServiceServer will
// result in compilation errors.
type UnsafeAdminServiceServer interface {
	mustEmbedUnimplementedAdminServiceServer()
}

func RegisterAdminServiceServer(s grpc.ServiceRegistrar, srv AdminServiceServer) {
	// If the following call pancis, it indicates UnimplementedAdminServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdminService_ServiceDesc, srv)
}

func _AdminService_RecordUserCreated_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserCreatedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).RecordUserCreated(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_RecordUserCreated_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).RecordUserCreated(ctx, req.(*UserCreatedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_RecordUserUpdated_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserUpdatedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).RecordUserUpdated(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_RecordUserUpdated_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).RecordUserUpdated(ctx, req.(*UserUpdatedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_RecordUserDeleted_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserDeletedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).RecordUserDeleted(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_RecordUserDeleted_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).RecordUserDeleted(ctx, req.(*UserDeletedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GetUserEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetUserEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetUserEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetUserEvents(ctx, req.(*GetUserEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminService_ServiceDesc is the grpc.ServiceDesc for AdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "admin.AdminService",
	HandlerType: (*AdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RecordUserCreated",
			Handler:    _AdminService_RecordUserCreated_Handler,
		},
		{
			MethodName: "RecordUserUpdated",
			Handler:    _AdminService_RecordUserUpdated_Handler,
		},
		{
			MethodName: "RecordUserDeleted",
			Handler:    _AdminService_RecordUserDeleted_Handler,
		},
		{
			MethodName: "GetUserEvents",
			Handler:    _AdminService_GetUserEvents_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "admin.proto",
}
